using SkrabbleLt.Models;
using System.Collections.Generic;

namespace SkrabbleLt.InitialData
{
    public static class BoardInitialData
    {
        public static List<BoardCell> DataSeed => new List<BoardCell>
        {
            new BoardCell(0, 0, "3xW"), 
            new BoardCell(0, 1, "   "),
            new BoardCell(0, 2, "   "),
            new BoardCell(0, 3, "2xL"),
            new BoardCell(0, 4, "   "),
            new BoardCell(0, 5, "   "),
            new BoardCell(0, 6, "   "),
            new BoardCell(0, 7, "3xW"),
            new BoardCell(0, 8, "   "),
            new BoardCell(0, 9, "   "),
            new BoardCell(0, 10, "   "),
            new BoardCell(0, 11, "2xL"),
            new BoardCell(0, 12, "   "),
            new BoardCell(0, 13, "   "),
            new BoardCell(0, 14, "3xW"),

            new BoardCell(1, 0, "   "),
            new BoardCell(1, 1, "2xW"),
            new BoardCell(1, 2, "   "),
            new BoardCell(1, 3, "   "),
            new BoardCell(1, 4, "   "),
            new BoardCell(1, 5, "3xL"),
            new BoardCell(1, 6, "   "),
            new BoardCell(1, 7, "   "),
            new BoardCell(1, 8, "   "),
            new BoardCell(1, 9, "3xL"),
            new BoardCell(1, 10, "   "),
            new BoardCell(1, 11, "   "),
            new BoardCell(1, 12, "   "),
            new BoardCell(1, 13, "2xW"),
            new BoardCell(1, 14, "   "),

            new BoardCell(2, 0, "   "),
            new BoardCell(2, 1, "   "),
            new BoardCell(2, 2, "2xW"),
            new BoardCell(2, 3, "   "),
            new BoardCell(2, 4, "   "),
            new BoardCell(2, 5, "   "),
            new BoardCell(2, 6, "2xL"),
            new BoardCell(2, 7, "   "),
            new BoardCell(2, 8, "2xL"),
            new BoardCell(2, 9, "   "),
            new BoardCell(2, 10, "   "),
            new BoardCell(2, 11, "   "),
            new BoardCell(2, 12, "2xW"),
            new BoardCell(2, 13, "   "),
            new BoardCell(2, 14, "   "),

            new BoardCell(3, 0, "2xL"),
            new BoardCell(3, 1, "   "),
            new BoardCell(3, 2, "   "),
            new BoardCell(3, 3, "2xW"),
            new BoardCell(3, 4, "   "),
            new BoardCell(3, 5, "   "),
            new BoardCell(3, 6, "   "),
            new BoardCell(3, 7, "2xL"),
            new BoardCell(3, 8, "   "),
            new BoardCell(3, 9, "   "),
            new BoardCell(3, 10, "   "),
            new BoardCell(3, 11, "2xW"),
            new BoardCell(3, 12, "   "),
            new BoardCell(3, 13, "   "),
            new BoardCell(3, 14, "2xL"),

            new BoardCell(4, 0, "   "),
            new BoardCell(4, 1, "   "),
            new BoardCell(4, 2, "   "),
            new BoardCell(4, 3, "   "),
            new BoardCell(4, 4, "2xW"),
            new BoardCell(4, 5, "   "),
            new BoardCell(4, 6, "   "),
            new BoardCell(4, 7, "   "),
            new BoardCell(4, 8, "   "),
            new BoardCell(4, 9, "   "),
            new BoardCell(4, 10, "2xW"),
            new BoardCell(4, 11, "   "),
            new BoardCell(4, 12, "   "),
            new BoardCell(4, 13, "   "),
            new BoardCell(4, 14, "   "),

            new BoardCell(5, 0, "   "),
            new BoardCell(5, 1, "3xL"),
            new BoardCell(5, 2, "   "),
            new BoardCell(5, 3, "   "),
            new BoardCell(5, 4, "   "),
            new BoardCell(5, 5, "3xL"),
            new BoardCell(5, 6, "   "),
            new BoardCell(5, 7, "   "),
            new BoardCell(5, 8, "   "),
            new BoardCell(5, 9, "3xL"),
            new BoardCell(5, 10, "   "),
            new BoardCell(5, 11, "   "),
            new BoardCell(5, 12, "   "),
            new BoardCell(5, 13, "3xL"),
            new BoardCell(5, 14, "   "),
            
            new BoardCell(6, 0, "   "),
            new BoardCell(6, 1, "   "),
            new BoardCell(6, 2, "2xL"),
            new BoardCell(6, 3, "   "),
            new BoardCell(6, 4, "   "),
            new BoardCell(6, 5, "   "),
            new BoardCell(6, 6, "2xL"),
            new BoardCell(6, 7, "   "),
            new BoardCell(6, 8, "2xL"),
            new BoardCell(6, 9, "   "),
            new BoardCell(6, 10, "   "),
            new BoardCell(6, 11, "   "),
            new BoardCell(6, 12, "2xL"),
            new BoardCell(6, 13, "   "),
            new BoardCell(6, 14, "   "),

            new BoardCell(7, 0, "3xW"),
            new BoardCell(7, 1, "   "),
            new BoardCell(7, 2, "   "),
            new BoardCell(7, 3, "2xL"),
            new BoardCell(7, 4, "   "),
            new BoardCell(7, 5, "   "),
            new BoardCell(7, 6, "   "),
            new BoardCell(7, 7, "2xW"),
            new BoardCell(7, 8, "   "),
            new BoardCell(7, 9, "   "),
            new BoardCell(7, 10, "   "),
            new BoardCell(7, 11, "2xL"),
            new BoardCell(7, 12, "   "),
            new BoardCell(7, 13, "   "),
            new BoardCell(7, 14, "3xW"),

            new BoardCell(8, 0, "   "),
            new BoardCell(8, 1, "   "),
            new BoardCell(8, 2, "2xL"),
            new BoardCell(8, 3, "   "),
            new BoardCell(8, 4, "   "),
            new BoardCell(8, 5, "   "),
            new BoardCell(8, 6, "2xL"),
            new BoardCell(8, 7, "   "),
            new BoardCell(8, 8, "2xL"),
            new BoardCell(8, 9, "   "),
            new BoardCell(8, 10, "   "),
            new BoardCell(8, 11, "   "),
            new BoardCell(8, 12, "2xL"),
            new BoardCell(8, 13, "   "),
            new BoardCell(8, 14, "   "),

            new BoardCell(9, 0, "   "),
            new BoardCell(9, 1, "3xL"),
            new BoardCell(9, 2, "   "),
            new BoardCell(9, 3, "   "),
            new BoardCell(9, 4, "   "),
            new BoardCell(9, 5, "3xL"),
            new BoardCell(9, 6, "   "),
            new BoardCell(9, 7, "   "),
            new BoardCell(9, 8, "   "),
            new BoardCell(9, 9, "3xL"),
            new BoardCell(9, 10, "   "),
            new BoardCell(9, 11, "   "),
            new BoardCell(9, 12, "   "),
            new BoardCell(9, 13, "3xL"),
            new BoardCell(9, 14, "   "),

            new BoardCell(10, 0, "   "),
            new BoardCell(10, 1, "   "),
            new BoardCell(10, 2, "   "),
            new BoardCell(10, 3, "   "),
            new BoardCell(10, 4, "2xW"),
            new BoardCell(10, 5, "   "),
            new BoardCell(10, 6, "   "),
            new BoardCell(10, 7, "   "),
            new BoardCell(10, 8, "   "),
            new BoardCell(10, 9, "   "),
            new BoardCell(10, 10, "2xW"),
            new BoardCell(10, 11, "   "),
            new BoardCell(10, 12, "   "),
            new BoardCell(10, 13, "   "),
            new BoardCell(10, 14, "   "),

            new BoardCell(11, 0, "2xL"),
            new BoardCell(11, 1, "   "),
            new BoardCell(11, 2, "   "),
            new BoardCell(11, 3, "2xW"),
            new BoardCell(11, 4, "   "),
            new BoardCell(11, 5, "   "),
            new BoardCell(11, 6, "   "),
            new BoardCell(11, 7, "2xL"),
            new BoardCell(11, 8, "   "),
            new BoardCell(11, 9, "   "),
            new BoardCell(11, 10, "   "),
            new BoardCell(11, 11, "2xW"),
            new BoardCell(11, 12, "   "),
            new BoardCell(11, 13, "   "),
            new BoardCell(11, 14, "2xL"),

            new BoardCell(12, 0, "   "),
            new BoardCell(12, 1, "   "),
            new BoardCell(12, 2, "2xW"),
            new BoardCell(12, 3, "   "),
            new BoardCell(12, 4, "   "),
            new BoardCell(12, 5, "   "),
            new BoardCell(12, 6, "2xL"),
            new BoardCell(12, 7, "   "),
            new BoardCell(12, 8, "2xL"),
            new BoardCell(12, 9, "   "),
            new BoardCell(12, 10, "   "),
            new BoardCell(12, 11, "   "),
            new BoardCell(12, 12, "2xW"),
            new BoardCell(12, 13, "   "),
            new BoardCell(12, 14, "   "),

            new BoardCell(13, 0, "   "),
            new BoardCell(13, 1, "2xW"),
            new BoardCell(13, 2, "   "),
            new BoardCell(13, 3, "   "),
            new BoardCell(13, 4, "   "),
            new BoardCell(13, 5, "3xL"),
            new BoardCell(13, 6, "   "),
            new BoardCell(13, 7, "   "),
            new BoardCell(13, 8, "   "),
            new BoardCell(13, 9, "3xL"),
            new BoardCell(13, 10, "   "),
            new BoardCell(13, 11, "   "),
            new BoardCell(13, 12, "   "),
            new BoardCell(13, 13, "2xW"),
            new BoardCell(13, 14, "   "),

            new BoardCell(14, 0, "3xW"),
            new BoardCell(14, 1, "   "),
            new BoardCell(14, 2, "   "),
            new BoardCell(14, 3, "2xL"),
            new BoardCell(14, 4, "   "),
            new BoardCell(14, 5, "   "),
            new BoardCell(14, 6, "   "),
            new BoardCell(14, 7, "3xW"),
            new BoardCell(14, 8, "   "),
            new BoardCell(14, 9, "   "),
            new BoardCell(14, 10, "   "),
            new BoardCell(14, 11, "2xL"),
            new BoardCell(14, 12, "   "),
            new BoardCell(14, 13, "   "),
            new BoardCell(14, 14, "3xW"),
        };
    }
}
